/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment.GUI;

import Assignment.Objects.Appointment;
import Assignment.Repositories.AppointmentRepository;
import Assignment.Repositories.UserRepository;
import Assignment.Objects.User;
import Assignment.status.STATUS;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

//import static sun.jvm.hotspot.debugger.win32.coff.DebugVC50X86RegisterEnums.STATUS;

/**
 * @author Hp
 */
public class rescheduleGUI extends javax.swing.JFrame {

    /**
     * Creates new form student_signedIn
     */
    public rescheduleGUI(String accountName, String accountID, String choseAppointmentID, String lecturerName) {
        initComponents(accountName, accountID, choseAppointmentID, lecturerName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(String accountName, String accountID, String choseAppointmentID, String lecturerName) {

        jSeparator2 = new javax.swing.JSeparator();
        history = new javax.swing.JLabel();
        feedback = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        appointment = new javax.swing.JLabel();
        timeSlot_consult = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        picHolder = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        IDlabel = new javax.swing.JLabel();
        textFieldID = new javax.swing.JTextField();
        lectureNameLabel = new javax.swing.JLabel();
        lecturerDropdown = new javax.swing.JComboBox<>();
        timeSlotLabel = new javax.swing.JLabel();
        timeSlotDropdown = new javax.swing.JComboBox<>();
        reasonLable = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        dateDropdown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        reasonInput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        isStudent = accountID.startsWith("S");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        history.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        history.setText("History");
        history.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt, accountName, accountID);
            }
        });

        feedback.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        feedback.setText("Feedback");
        feedback.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackMouseClicked(evt, accountName, accountID);
            }
        });

        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt, accountName, accountID);
            }
        });

        appointment.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        appointment.setText("Appointment");
        appointment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentMouseClicked(evt, accountName, accountID);
            }
        });

        timeSlot_consult.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        String text = isStudent ? "Consult" : "Time Slot";
        timeSlot_consult.setText(text);
        timeSlot_consult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        timeSlot_consult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultMouseClicked(evt, accountName, accountID);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));


        name.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        name.setText(accountName);

        id.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        id.setText(accountID);

        ImageIcon profilePic = new ImageIcon("src/main/java/Assignment/image/profile_pic_50x50.png");
        picHolder.setIcon(profilePic);
        picHolder.setText("");

        ImageIcon exitPic = new ImageIcon("src/main/java/Assignment/image/sign_out.png");
        exit.setIcon(exitPic);
        exit.setText("");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });


        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLabel.setText("Name:");

        textFieldName.setEditable(false);
        textFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldName.setText(accountName);

        IDlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IDlabel.setText("ID:");

        textFieldID.setEditable(false);
        textFieldID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldID.setText(accountID);


        lectureNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lectureNameLabel.setText("Lecturer:");

        lecturerDropdown.setEditable(true);
        lecturerDropdown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        lecturerDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        for (User line : userList) {
            if (line.accountID.startsWith("L")) {
                lecturerDropdown.addItem(line.accountName);
            }
        }
//        System.out.println(appointmentList.size());
        comboBoxFilter(lecturerName);


        timeSlotLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timeSlotLabel.setText("Time Slot:");

        timeSlotDropdown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        timeSlotDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        timeSlotDropdown.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getSelectedTime();
            }
        });

        reasonLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reasonLable.setText("Reason:");

        confirmButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmButton.setText("Submit");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt,accountName ,accountID, choseAppointmentID);
            }
        });

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateLabel.setText("Date:");

        dateDropdown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        dateDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateDropdown.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getSelectedDate();
            }
        });

        reasonInput.setColumns(20);
        reasonInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reasonInput.setRows(10);

        reasonInput.setLineWrap(true);
        jScrollPane1.setViewportView(reasonInput);
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(picHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(exit)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(picHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(name)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(id))))
                                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(dashboard)
                                                        .addComponent(history)
                                                        .addComponent(feedback)
                                                        .addComponent(appointment)
                                                        .addComponent(timeSlot_consult)))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(confirmButton)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(IDlabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(timeSlotDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(reasonLable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lectureNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(4, 4, 4)
                                                                .addComponent(lecturerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(32, 32, 32)
                                                                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(dateDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(timeSlotLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addComponent(appointment, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addComponent(timeSlot_consult, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 18, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDlabel)
                                        .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lectureNameLabel)
                                        .addComponent(timeSlotLabel)
                                        .addComponent(timeSlotDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateLabel)
                                        .addComponent(lecturerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reasonLable)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmButton)
                                .addGap(33, 33, 33))
        );
        pack();
    }// </editor-fold>

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {
        int selection = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to logout...");
        if (selection == JOptionPane.YES_OPTION) {
            loginGUI login = new loginGUI();
            login.setVisible(true);
            this.dispose();
        }
    }

    private void comboBoxFilter(String name) {

            lecturerDropdown.setEnabled(false);
            lecturerDropdown.setSelectedItem(name);
            choseLecturerName = name;


        System.out.println(choseLecturerName);
        dateDropdown.removeAllItems();
        for (User line : userList) {
            if (line.accountName.equals(choseLecturerName)) {
                lectureID = line.accountID;

                break;
            }
        }

        for (Appointment appointment : appointmentList) {
            if (appointment.lecturerID.equals(lectureID) && appointment.status.equals(String.valueOf(STATUS.Available))) {
                dateDropdown.addItem(appointment.date);
            }

        }
    }

    private void getSelectedDate() {
        selectedDate = (String) dateDropdown.getSelectedItem();
        timeSlotDropdown.removeAllItems();
        System.out.println(lectureID);
        for (Appointment appointment : appointmentList) {
//            System.out.printf("%b, %b, %b\n", appointment.lecturerID.equals(lectureID), appointment.status.equals(String.valueOf(STATUS.Available)), appointment.date.equals(selectedDate));
            if (appointment.lecturerID.equals(lectureID) && appointment.status.equals(String.valueOf(STATUS.Available)) && appointment.date.equals(selectedDate)) {
                timeSlotDropdown.addItem(String.format("%s - %s", appointment.startTime, appointment.endTime));
            }
        }
    }

    private void getSelectedTime() {
        chooseTimeRange = (String) timeSlotDropdown.getSelectedItem();
//        System.out.printf("%s %s\n", selectedDate, selectedTime);
    }

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt, String accountName, String accountID) {
        // TODO add your handling code here:
        dashboardGUI obj = new dashboardGUI(accountName, accountID);
        obj.setVisible(true);
        this.dispose();
    }

    private void historyMouseClicked(java.awt.event.MouseEvent evt, String accountName, String accountID) {
        // TODO add your handling code here:
        historyGUI obj = new historyGUI(accountName, accountID);
        obj.setVisible(true);
        this.dispose();

    }

    private void feedbackMouseClicked(java.awt.event.MouseEvent evt, String accountName, String accountID) {
        // TODO add your handling code here:
        feedbackGUI obj = new feedbackGUI(accountName, accountID);
        obj.setVisible(true);
        this.dispose();
    }

    private void appointmentMouseClicked(java.awt.event.MouseEvent evt, String accountName, String accountID) {
        // TODO add your handling code here:
        appointmentGUI obj = new appointmentGUI(accountName, accountID);
        obj.setVisible(true);
        this.dispose();
    }

    private void consultMouseClicked(java.awt.event.MouseEvent evt, String accountName, String accountID) {
        if (isStudent) {
            studentConsultGUI obj = new studentConsultGUI(accountName, accountID);
            obj.setVisible(true);
        }else{
            lecturerSetApptGUI obj = new lecturerSetApptGUI(accountName, accountID);
            obj.setVisible(true);
        }this.dispose();
    }

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt, String accountName, String accountID, String appointmentID) {
        selectedTime = chooseTimeRange.split("-")[0].trim();
        System.out.printf("%s,%s,%s\n", lectureID, selectedDate, selectedTime);
        String reason = reasonInput.getText();
        if (reason.contains(",")) {
            reason = reason.replace(",", "$COMMA$");
        }
        String purpose = "";
        for (Appointment line : appointmentList) {
            if (line.apptID.equals(appointmentID)){
                line.studentID = "-";
                purpose = line.purpose;
                line.purpose = "-";
                line.status = String.valueOf(STATUS.Available);
                line.lecturerFeed = "-";
                continue;
            }

            if (line.lecturerID.equals(lectureID) && line.date.equals(selectedDate) && line.startTime.equals(selectedTime)) {
                System.out.printf("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n", line.apptID, line.date, line.startTime, line.endTime, line.purpose, line.studentID, line.lecturerID, line.status, line.studentFeed, line.lecturerFeed);
                line.purpose = purpose;
                line.studentID = accountID;
                line.status = String.valueOf(STATUS.Pending);
                line.studentRescheduleReason = reason;
//                System.out.println(List.of(line));
                break;
            }
        }
        appointmentRepo.modifyAppointment(appointmentList);
        JOptionPane.showMessageDialog(rootPane, "Appointment have been reschedule, waiting for approval");
        appointmentGUI obj = new appointmentGUI(accountName, accountID);
        obj.setVisible(true);
        this.dispose();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rescheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rescheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rescheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rescheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rescheduleGUI("", "", "", "").setVisible(true);
//                new appointmentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel IDlabel;
    private javax.swing.JLabel appointment;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel timeSlot_consult;
    private javax.swing.JLabel dashboard;
    private javax.swing.JComboBox<String> dateDropdown;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel feedback;
    private javax.swing.JLabel history;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea reasonInput;
    private javax.swing.JLabel lectureNameLabel;
    private javax.swing.JComboBox<String> lecturerDropdown;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel picHolder;
    private javax.swing.JLabel reasonLable;
    private javax.swing.JTextField textFieldID;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JComboBox<String> timeSlotDropdown;
    private javax.swing.JLabel timeSlotLabel;
    private String lectureID, selectedDate, selectedTime, chooseTimeRange, choseLecturerName;
    private boolean isStudent;
    private UserRepository userRepo = new UserRepository();
    private AppointmentRepository appointmentRepo = new AppointmentRepository();
    private final List<User> userList = userRepo.getUsers();
    private final List<Appointment> appointmentList = appointmentRepo.getAppointment();
// End of variables declaration
}
